exports.superAdminPermission = {
  canCreateAdmin: true,
  canReadAdmin: true,
  canUpdateAdmin: true,
  canDeleteAdmin: true,
  canBlockAdmin: true,
  canUpdatePermissions: true,
  canCreateUser: true,
  canReadUser: true,
  canUpdateUser: true,
  canDeleteUser: true,
  canBlockUser: true,
  canCreateMember: true,
  canReadMember: true,
  canUpdateMember: true,
  canDeleteMember: true,
  canBlockMember: true,
};

exports.adminPermission = {
  canCreateAdmin: false,
  canReadAdmin: false,
  canUpdateAdmin: false,
  canDeleteAdmin: false,
  canBlockAdmin: false,
  canUpdatePermissions: false,
  canCreateUser: false,
  canReadUser: false,
  canUpdateUser: false,
  canDeleteUser: false,
  canBlockUser: false,
  canCreateMember: false,
  canReadMember: false,
  canUpdateMember: false,
  canDeleteMember: false,
  canBlockMember: false,
};

exports.MemberPermission = {
  canCreateAdmin: false,
  canReadAdmin: false,
  canUpdateAdmin: false,
  canDeleteAdmin: false,
  canBlockAdmin: false,
  canUpdatePermissions: false,
  canCreateUser: false,
  canReadUser: false,
  canUpdateUser: false,
  canDeleteUser: false,
  canBlockUser: false,
  canCreateMember: false,
  canReadMember: false,
  canUpdateMember: false,
  canDeleteMember: false,
  canBlockMember: false,
}

exports.UserPermission = {
  canCreateAdmin: false,
  canReadAdmin: false,
  canUpdateAdmin: false,
  canDeleteAdmin: false,
  canBlockAdmin: false,
  canUpdatePermissions: false,
  canCreateUser: false,
  canReadUser: false,
  canUpdateUser: false,
  canDeleteUser: false,
  canBlockUser: false,
  canCreateMember: false,
  canReadMember: false,
  canUpdateMember: false,
  canDeleteMember: false,
  canBlockMember: false,
}