exports.superAdminPermission = {
  canCreateAdmin: true,
  canReadAdmin: true,
  canUpdateAdmin: true,
  canDeleteAdmin: true,
  canBlockAdmin: true,
  canUpdatePermissions: true,
  canCreateUser: true,
  canReadUser: true,
  canUpdateUser: true,
  canDeleteUser: true,
  canBlockUser: true,
  canCreateStaff: true,
  canReadStaff: true,
  canUpdateStaff: true,
  canDeleteStaff: true,
  canBlockStaff: true,
  canCreateProperty: true,
  canReadProperty: true,
  canUpdateProperty: true,
  canDeleteProperty: true,
  canCreateApartment: true,
  canReadApartment: true,
  canUpdateApartment: true,
  canDeleteApartment: true,
  canCreateBranches:true,
  canReadBranches: true,
  canUpdateBranches: true,
  canDeleteBranches: true,
};

exports.adminPermission = {
  canCreateAdmin: false,
  canReadAdmin: false,
  canUpdateAdmin: false,
  canDeleteAdmin: false,
  canBlockAdmin: false,
  canUpdatePermissions: false,
  canCreateUser: false,
  canReadUser: false,
  canUpdateUser: false,
  canDeleteUser: false,
  canBlockUser: false,
  canCreateStaff: false,
  canReadStaff: false,
  canUpdateStaff: false,
  canDeleteStaff: false,
  canBlockStaff: false,
  canCreateProperty: false,
  canReadProperty: false,
  canUpdateProperty: false,
  canDeleteProperty: false,
  canCreateApartment: false,
  canReadApartment: false,
  canUpdateApartment: false,
  canDeleteApartment: false,
  canCreateBranches:false,
  canReadBranches: false,
  canUpdateBranches: false,
  canDeleteBranches: false,
};

exports.StaffPermission = {
  canCreateAdmin: false,
  canReadAdmin: false,
  canUpdateAdmin: false,
  canDeleteAdmin: false,
  canBlockAdmin: false,
  canUpdatePermissions: false,
  canCreateUser: false,
  canReadUser: false,
  canUpdateUser: false,
  canDeleteUser: false,
  canBlockUser: false,
  canCreateStaff: false,
  canReadStaff: false,
  canUpdateStaff: false,
  canDeleteStaff: false,
  canBlockStaff: false,
  canCreateProperty: false,
  canReadProperty: false,
  canUpdateProperty: false,
  canDeleteProperty: false,
  canCreateApartment: false,
  canReadApartment: false,
  canUpdateApartment: false,
  canDeleteApartment: false,
  canCreateBranches:false,
  canReadBranches: false,
  canUpdateBranches: false,
  canDeleteBranches: false,
}

exports.UserPermission = {
  canCreateAdmin: false,
  canReadAdmin: false,
  canUpdateAdmin: false,
  canDeleteAdmin: false,
  canBlockAdmin: false,
  canUpdatePermissions: false,
  canCreateUser: false,
  canReadUser: false,
  canUpdateUser: false,
  canDeleteUser: false,
  canBlockUser: false,
  canCreateStaff: false,
  canReadStaff: false,
  canUpdateStaff: false,
  canDeleteStaff: false,
  canBlockStaff: false,
  canCreateProperty: false,
  canReadProperty: false,
  canUpdateProperty: false,
  canDeleteProperty: false,
  canCreateApartment: false,
  canReadApartment: false,
  canUpdateApartment: false,
  canDeleteApartment: false,
  canCreateBranches:false,
  canReadBranches: false,
  canUpdateBranches: false,
  canDeleteBranches: false,
}